baseURL = "http://example.org/"
languageCode = "en-us"
title = "Nika Khanjani :: Filmmaker & More"
theme = "simplecard2021"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
